name: file_selector_ios
publish_to: none
description: iOS implementation of the file_selector plugin.
repository: https://github.com/flutter/packages/tree/main/packages/file_selector/file_selector_ios
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+file_selector%22
version: 0.5.3+1

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: file_selector
    platforms:
      ios:
        dartPluginClass: FileSelectorIOS
        pluginClass: FileSelectorPlugin

dependencies:
  file_selector_platform_interface:
    git: https://github.com/kumsumit/file_selector_platform_interface.git
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon:
    git: https://github.com/kumsumit/pigeon.git

topics:
  - files
  - file-selection
  - file-selector
